version: "3"
services:
  expo:
    container_name: expo-drowsy-detection
    build: ./react-native-client
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    volumes:
      # - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=*LOCAL IPV4 IP*
    networks:
      - docker_network

  rest-api:
    build:
      context: ./rest-api-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - drowsydetectiondb
    environment:
      JWT_TOKEN_SECRET: ioajdfoiajfaoidjfo
      DATABASE_URL: postgres://root:123456@drowsydetectiondb:5432/drowsy_detection_db
      NODE_PRODUCTION: development
    volumes:
      - /usr/src/app/node_modules
    networks:
      - docker_network

  drowsy-detection:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - docker_network

  drowsydetectiondb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    # ports:
    #   - "5437:5432"
    volumes:
      # - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./rest-api-server/sql:/docker-entrypoint-initdb.d
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
